stages:
  - Build and Deploy
env:
  - APP1="Secrets"
matrix:
  include:
    - stage: Build and Deploy
      script: 
        - echo "new app value:"
        - chmod 755 script.sh
        - bash -x ./script.sh
        - echo "${APP1}"

