stages:
  - Build and Deploy
env:
  global:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then APP1="master-app"; fi
    - if [ "$TRAVIS_BRANCH" = "target" ]; then APP1="target-app"; fi
matrix:
  include:
    - stage: Build and Deploy
      script: 
        - if [ "$TRAVIS_BRANCH" = "master" ]; then echo "master"; fi
        - if [ "$TRAVIS_BRANCH" = "target" ]; then echo "target"; fi
        - echo "new app value:"
        - chmod 775 script.sh
        - . script.sh
        - . script1.sh
        - echo $APP
    - env:
        - ZONE="europe-west2-a"
      script:
        - echo "${APP1} and ${ZONE}"
