stages:
  - Build and Deploy
env:
  global:
    - APP1="Secrets"
matrix:
  include:
    - stage: Build and Deploy
      script: 
        - if [ "$TRAVIS_BRANCH" = "master" ]; then echo "master"; fi
        - if [ "$TRAVIS_BRANCH" = "master" ]; then echo "target"; fi
        - echo "new app value:"
        - chmod 755 script.sh
        - bash -x ./script.sh
        - echo "${APP1}"
    - env:
        - ZONE="europe-west2-a"
      script:
        - echo "${APP1} and ${ZONE}"
